apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: minex970/todo-app:v1
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: database_name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-cred
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-cred
              key: password
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
