apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: todo-ns
spec:
  selector:
    app: todo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
